//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabel.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drillhole_Sample
    {
        public string SAMPLEID { get; set; }
        public string HOLEID { get; set; }
        public string PROJECTCODE { get; set; }
        public string SAMPFROM { get; set; }
        public string SAMPTO { get; set; }
        public string SAMPLETYPE { get; set; }
        public string PRIORITY { get; set; }
        public string CoreCutDate { get; set; }
        public string Sample_Comments { get; set; }
    }
}
