//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabel.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillholesPlanning
    {
        public string HOLEID { get; set; }
        public string SAMPLEID { get; set; }
        public string PROJECTCODE { get; set; }
        public Nullable<double> SAMPFROM { get; set; }
        public Nullable<double> SAMPTO { get; set; }
        public Nullable<double> LL_WGS84_Calc_X { get; set; }
        public Nullable<double> LL_WGS84_Calc_Y { get; set; }
        public Nullable<double> ALTX1 { get; set; }
        public Nullable<double> ALTY1 { get; set; }
        public Nullable<double> ALTX2 { get; set; }
        public Nullable<double> ALTY2 { get; set; }
    }
}
