//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabel.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillholeSamplesView
    {
        public string HOLEID { get; set; }
        public string PROJECTCODE { get; set; }
        public string LL_WGS84_Calc_X { get; set; }
        public string LL_WGS84_Calc_Y { get; set; }
        public string LL_WGS84_Calc_Z { get; set; }
        public string TENEMENTID { get; set; }
        public string DEPTH { get; set; }
        public string PROSPECT { get; set; }
        public string STARTDATE { get; set; }
        public string ENDDATE { get; set; }
        public string CostCentre { get; set; }
        public string Depth_RC { get; set; }
        public string DrillholeType { get; set; }
        public string DrillTargetDepth { get; set; }
        public string EndDate_DDH { get; set; }
        public string EndDate_RC { get; set; }
        public string GearDownHole { get; set; }
        public string Geologist { get; set; }
        public string HoleStatus { get; set; }
        public string PlannedDepth { get; set; }
        public string PlannedHoleID { get; set; }
        public string PlannedRCDepth { get; set; }
        public string RigType { get; set; }
        public string SAMPLEID { get; set; }
        public string SAMPFROM { get; set; }
        public string SAMPTO { get; set; }
        public string SAMPLETYPE { get; set; }
        public string PRIORITY { get; set; }
        public string CoreCutDate { get; set; }
        public string Sample_Comments { get; set; }
    }
}
