//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabel.Web.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elabelEntities : DbContext
    {
        public elabelEntities()
            : base("name=elabelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Laboratory_analysis> Laboratory_Analyses { get; set; }
        public virtual DbSet<Drillhole> Drillholes { get; set; }
        public virtual DbSet<Drillhole_Sample> Drillhole_Samples { get; set; }
        public virtual DbSet<DrillholeSamplesView> DrillholeSamplesViews { get; set; }
        public virtual DbSet<RecoveryInterval> RecoveryIntervals { get; set; }
        public virtual DbSet<ContaminationCheck> ContaminationChecks { get; set; }
        public virtual DbSet<standardReference> standardReferences { get; set; }
        public virtual DbSet<DrillholesPlanning> DrillholesPlannings { get; set; }
        public virtual DbSet<AlertGenerator> AlertGenerators { get; set; }
        public virtual DbSet<Label> Labels { get; set; }
        public virtual DbSet<RejectAlert> RejectAlerts { get; set; }
    }
}
