//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabel.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public string SampleID { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public string LastScanned { get; set; }
        public Nullable<bool> Scanned { get; set; }
        public Nullable<bool> IsTransferring { get; set; }
    }
}
