//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELabel.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryInterval
    {
        public string HOLEID { get; set; }
        public string PROJECTCODE { get; set; }
        public Nullable<double> GEOLFROM { get; set; }
        public Nullable<double> GEOLTO { get; set; }
        public Nullable<double> PRIORITY { get; set; }
        public Nullable<double> Recovery_m { get; set; }
        public string RecovGeo { get; set; }
        public Nullable<System.DateTime> RecovGeoDate { get; set; }
        public Nullable<double> CoreLength { get; set; }
        public Nullable<double> RecoveryRatio { get; set; }
        public int ID { get; set; }
    
        public virtual Drillhole Drillhole { get; set; }
    }
}
